name: Daily
on:
  schedule:
  - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  api-tests:
    name: IncusOS API tests
    strategy:
      fail-fast: false
    timeout-minutes: 360
    runs-on:
      - self-hosted
      - cpu-4
      - mem-8G
      - disk-100G
      - arch-amd64
      - image-debian-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Incus
        run: |
          curl https://pkgs.zabbly.com/get/incus-daily | sudo sh
          sudo chmod 666 /var/lib/incus/unix.socket
          incus admin init --auto

      - name: Run API tests
        run: |
          incus-osd/tests/api-tests.py
